name: Run Postman Collection


on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main


jobs:
  run-postman-tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.TIMILEHIN_QA_ASSIGNMENT }}


      - name: Run Postman collection
        run: |
          postman collection run "Assignment.postman_collection.json"
